apiVersion: v1
kind: Service
metadata:
  labels:
    service: rating-mysql
  name: rating-mysql
spec:
  ports:
  - name: rating-mysql
    port: 3306
    targetPort: 3306
  selector:
    service: rating-mysql
