apiVersion: v1
kind: Service
metadata:
  name: ratings
  labels:
    service: ratings
spec:
  #type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    service: ratings

