apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    service: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mysql
  template:
    metadata:
      labels:
        service: mysql
    spec:
      containers:
      - name: mysql
        image: rs-mysql-shipping-db:0.0.1
        env:
        #- name: MYSQL_ALLOW_EMPTY_PASSWORD
        #  value: yes
        - name: MYSQL_DATABASE
          value: cities
        - name: MYSQL_USER
          value: shipping
        - name: MYSQL_PASSWORD
          value: secret
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_ROOT_PASSWORD
          value: supersecret
        ports:
        - containerPort: 3306
        resources:
          limits:
            cpu: 200m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 700Mi
      restartPolicy: Always
