FROM nginx:stable-alpine
LABEL maintainer="prashant7july[at]gmail.com"

ENV CATALOGUE_HOST=catalogue \
    USER_HOST=user \
    CART_HOST=cart \
    SHIPPING_HOST=shipping \
    PAYMENT_HOST=payment \
    RATINGS_HOST=ratings

COPY default.conf.template /etc/nginx/conf.d/default.conf.template
COPY html/ /usr/share/nginx/html/
COPY entrypoint.sh /

CMD ["/entrypoint.sh"]
