apiVersion: v1
kind: Service
metadata:
  labels:
    service: catalogue-mongodb
  name: catalogue-mongodb
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  selector:
    service: catalogue-mongodb
