apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-mongodb
  labels:
    service: catalogue-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      service: catalogue-mongodb
  template:
    metadata:
      labels:
        service: catalogue-mongodb
    spec:
      containers:
      - name: catalogue-mongodb
        image: rs-catalogue-mongodb:0.0.1
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always
